//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Zakas = new HashSet<Zakas>();
        }
    
        public int Id_client { get; set; }
        public string Name { get; set; }
        public string Familyi { get; set; }
        public string Otchestvo { get; set; }
        public string Passport_data { get; set; }
        public System.DateTime Date_birthday { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakas> Zakas { get; set; }

        public string fullName
        {
            get
            {
                return $"{Familyi} {Name} {Otchestvo}";
            }
        }

    }
}
