//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igoraDb : DbContext
    {
        public igoraDb()
            : base("name=igoraDb")
        {
        }

        private static igoraDb _context;

        public static igoraDb GetContext()
        {

            if (_context == null)
                _context = new igoraDb();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Dolshosty> Dolshosty { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_vhoda> Tip_vhoda { get; set; }
        public virtual DbSet<Ysluga> Ysluga { get; set; }
        public virtual DbSet<Zakas> Zakas { get; set; }
        public virtual DbSet<Zakas_yslugi> Zakas_yslugi { get; set; }
    }
}
