//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int Id_sotrudnik { get; set; }
        public string Name { get; set; }
        public string Familyi { get; set; }
        public string Otchestvo { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id_dolshosty { get; set; }
        public int Id_tip_vhoda { get; set; }
        public System.DateTime Time_poslednego_vhoda { get; set; }
    
        public virtual Dolshosty Dolshosty { get; set; }
        public virtual Tip_vhoda Tip_vhoda { get; set; }
    }
}
