//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ysluga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ysluga()
        {
            this.Zakas_yslugi = new HashSet<Zakas_yslugi>();
        }
    
        public int Id_Ysluga { get; set; }
        public string Name { get; set; }
        public string Kod_yslugi { get; set; }
        public double Stoimosty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakas_yslugi> Zakas_yslugi { get; set; }
    }
}
