//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakas_yslugi
    {
        public int Id_zakas_yslugi { get; set; }
        public int Id_ysluga { get; set; }
        public int Id_Zakas { get; set; }
    
        public virtual Ysluga Ysluga { get; set; }
        public virtual Zakas Zakas { get; set; }
    }
}
