//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakas()
        {
            this.Zakas_yslugi = new HashSet<Zakas_yslugi>();
        }
    
        public int Id_zakas { get; set; }
        public System.DateTime Date_create { get; set; }
        public string Kod_zakasa { get; set; }
        public System.TimeSpan Time_zakasa { get; set; }
        public int Id_client { get; set; }
        public int Time_prokat { get; set; }
        public Nullable<System.DateTime> Date_close { get; set; }
        public int Id_status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakas_yslugi> Zakas_yslugi { get; set; }
    }
}
